# Generated by Django 3.2.25 on 2025-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
