# Generated by Django 3.2.25 on 2025-05-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_customerservice_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerservice',
            unique_together=set(),
        ),
    ]
