# Generated by Django 3.2.25 on 2025-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customerservice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
