# Generated by Django 3.2.25 on 2025-05-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customerservice_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Employee',
        ),
    ]
